global:
  scrape_interval: 15s
rule_files:
  - "prometheus.rules.yml"
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      # Sử dụng tên service trong docker-compose làm target
      - targets: ['node-exporter:9100']

  - job_name: 'ml-api'
    metrics_path: /metrics
    static_configs:
      # Sử dụng tên service trong docker-compose làm target
      - targets: ['ml-api:8888']
